version: '3.8'
services:
  adaptive-graph-of-thoughts:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - NEO4J_DATABASE=neo4j
    depends_on:
      - neo4j
    
  neo4j:
    image: neo4j:5.15-community
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
