site_name: Adaptive Graph of Thoughts Documentation
docs_dir: docs_src
site_url: https://SaptaDey.github.io/Adaptive-Graph-of-Thoughts-MCP-server/
repo_url: https://github.com/SaptaDey/Adaptive-Graph-of-Thoughts-MCP-server
repo_name: Adaptive-Graph-of-Thoughts-MCP-server

theme:
  name: material
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.indexes
    - navigation.expand
    - header.autohide
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: amber
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
      accent: orange

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Configuration: configuration.md
  - Usage: usage.md
  - API Reference: 
    - MCP API: api/mcp_api.md
  - Extending Adaptive Graph of Thoughts:
    - Custom Stages: extending/custom_stages.md # Placeholder
    - Claude API Integration: extending_with_claude.md
  - Contributing: CONTRIBUTING.md
  - Roadmap: ROADMAP.md
  # - License: LICENSE.md # Assuming LICENSE.md exists or will be added - Removed as LICENSE.md does not exist
  # - Status Page Info: status_info.md # For status.html content

extra_css:
  - assets/stylesheets/custom.css
extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js
