# Main Application Settings for Adaptive Graph of Thoughts
app:
  name: "Adaptive Graph of Thoughts"
  version: "0.1.0"
  host: "0.0.0.0"
  port: 8000
  mcp_transport_type: "http"
  mcp_stdio_enabled: true
  mcp_http_enabled: true
  log_level: "INFO"

asr_got:
  default_parameters: {}

mcp_settings:
  protocol_version: "2024-11-05"
  server_name: "Adaptive Graph of Thoughts MCP Server"
  server_version: "0.1.0"
  vendor_name: "Adaptive Graph of Thoughts Development Team"

# Optional API configurations
google_scholar:
  api_key: "YOUR_GOOGLE_SCHOLAR_API_KEY_HERE"
  base_url: "https://serpapi.com/search"

pubmed:
  api_key: "YOUR_PUBMED_API_KEY_HERE_IF_NEEDED"
  base_url: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
  email: "your_email@example.com"

exa_search:
  api_key: "YOUR_EXA_SEARCH_API_KEY_HERE"
  base_url: "https://api.exa.ai"

knowledge_domains:
  - name: "Skin Immunology"
    keywords: ["skin", "immune"]
    description: "Focuses on the immune responses and mechanisms within the skin."
