name: "Generic MCP Client Configuration"
description: "Universal configuration template for MCP clients"
servers:
  adaptive-graph-of-thoughts:
    transport: stdio
    command: python
    args:
      - -m
      - adaptive_graph_of_thoughts.main
    cwd: /path/to/Adaptive-Graph-of-Thoughts-MCP-server
    env:
      NEO4J_URI: bolt://localhost:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: your_password
      NEO4J_DATABASE: neo4j
      MCP_TRANSPORT_TYPE: stdio
      LOG_LEVEL: INFO
      PYTHONPATH: /path/to/Adaptive-Graph-of-Thoughts-MCP-server/src
