name: Lint and Type Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set up git credentials for private repos
        run: git config --global url."https://${{ secrets.TOKEN_GITHUB }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - uses: pre-commit/action@v3.0.1
